version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y python3 python3-pip
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo "Building..."
      - terraform init
      - terraform plan
  post_build:
    commands:
      - terraform apply -auto-approve
