version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install -r requirements.txt
      - terraform init
  build:
    commands:
      - terraform plan -out=tfplan
  post_build:
    commands:
      - terraform apply tfplan
artifacts:
  files:
    - '**/*'
