version: 0.2
phases:
  install:
    commands:
      - |
        echo -e "## DEPLOYING TERRAFORM RESOURCES ##"
  build:
    commands:
      - echo "Retrieving the plan from S3..."
      - aws s3 cp s3://your-bucket-name/tfplan tfplan
      - terraform init
      - terraform apply -auto-approve tfplan
  post_build:
    commands:
      - echo "Apply stage complete."
artifacts:
  files:
    - tfplan