version: 0.2
phases:
  install:
    commands:
      - |
        echo -e "## DEPLOYING TERRAFORM RESOURCES ##"
  build:
    commands:
      - echo "initializing terraform..."
      - terraform init
      - terraform apply -auto-approve tfplan
  post_build:
    commands:
      - echo "Apply stage complete."
# artifacts:
#   files:
#     - tfplan