version: 0.2
phases:
  install:
    commands:
      - |
        echo "[]## PRE DEPLOYMENT CHECKER \##"
      - |
        echo "[]configuring environment..."
      - whoami
      - echo $SHELL
      - which sh || sudo apk add bash
      - apk update
      - apk add jq
      - |
        if [ $? -eq 0 ]; then
          echo "[]complete."
          startBuild=Starting
        else
          startBuild=Attempting
          echo "[warning]:configuration failed!"
        fi
  build:
    commands:
      - |
        echo ""
      - echo -e "[]$startBuild Terraform pre-deployment checks..\n"
      - echo "[]Running tf validate..."
      - terraform init -backend=false
      - terraform validate -json
      - echo -e "[]tf validate complete.\n"
      - |
        validation_out=$(terraform validate -json)
        valid=$(echo $validation_out | jq -r .valid)
        warning_count=$(echo $validation_out | jq -r .warning_count)
        if [ "$valid" = "true" ]; then
          echo "[tfValidate]successfull with $warning_count warnings."
        else
          echo "[tfValidate]$warning_count warnings found."
          echo "[tfValidate]Fatal error: Validation failed."
          echo "[env]Exiting preflight checks..."
          exit 1
        fi
      - |
        terraform init
      - |
        terraform plan -out=tfplan
  post_build:
    commands:
      - |
        echo "exiting preflight..."
artifacts:
  files:
    - tfplan
